### ISSUE TITLE
cose da ultimare

### ISSUE THREAD

**Issue by Ovial-lab** [Ovial-lab/orgInternaz#7]
-gestione pagamenti (front-end)
-Inserimento query di base sull'interfaccia con menu a tendina delle nazioni e tipologie
-gestione successivi pagamenti per abbonamento a rate
-ALLA FINE DI TUTTO RICONTROLLARE CSS E ADATTARLO UGUALMENTE A TUTTE LE PAGINE(font)

**Comment by POPHD3000** [comment]
Issue reputata chiusa, l'unico punto da dover ancora sistemare è già nominato nell'altra issue.
